<?php
/**
 * Created by PhpStorm.
 * User: ssw
 * Date: 2016/5/17
 * Time: 17:16
 */
namespace app\controllers;

use Yii;
use app\components\Uploader;

class UploadController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if($this->action->id == 'editor'){
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionEditor()
    {
        $action = \Yii::$app->request->get('action');
        $CONFIG = json_decode(preg_replace("/\/\*[\s\S]+?\*\//", "", file_get_contents(\Yii::getAlias('@app') . "/components/config.json")), true);
        switch ($action) {
            case 'config':
                return json_encode($CONFIG);
                return $CONFIG;
            case 'uploadimage';
                $config = array(
                    "pathFormat" => $CONFIG['imagePathFormat'],
                    "maxSize" => $CONFIG['imageMaxSize'],
                    "allowFiles" => $CONFIG['imageAllowFiles']
                );
                $fieldName = $CONFIG['imageFieldName'];
                $base64 = 'upload';
                $upload = new Uploader($fieldName, $config, $base64);
                return $result = json_encode($upload->getFileInfo());
        }
    }


}